/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.bean.TempoLigado;
import model.dao.TempoLigadoDAO;
import utils.ArduinoSerial;


import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.annotation.JsonMerge;
import dataFromArduino.ArduinoData;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author leand
 */
public class ViewEstado extends javax.swing.JFrame {

    /**
     * Creates new form ViewEstado
     */
    public ViewEstado() {
        initComponents();
        
        ArduinoSerial arduino = new ArduinoSerial("COM3");
        TempoLigadoDAO tDao = new TempoLigadoDAO();
        int diaAtual = tDao.getLastDayInserted() + 1;
        Thread t = new Thread() {
            @Override
            public void run() {
                //super.run(); //To change body of generated methods, choose Tools | Templates.
                arduino.initialize();
                
                while (true) {                    
                    
                    String arduinoCurrentState = arduino.read();
                    System.out.println(arduinoCurrentState);
                    if ( arduinoCurrentState != null ) {

                        ObjectMapper mapper = new ObjectMapper();
                        ArduinoData[] ad = null;
                        try {
                            ad = mapper.readValue(arduinoCurrentState, ArduinoData[].class);
                        } catch (IOException ex) {
                            ex.printStackTrace();
                        }

                        for (ArduinoData data : ad) {
                            TempoLigado tempoLigado1 = new TempoLigado();
                            tempoLigado1.setDia(diaAtual);
                            tempoLigado1.setPotencia(data.getLed1());
                            tDao.create(tempoLigado1);
                            
                            TempoLigado tempoLigado2 = new TempoLigado();
                            tempoLigado2.setDia(diaAtual);
                            tempoLigado2.setPotencia(data.getLed2());
                            tDao.create(tempoLigado2);
                            
                            TempoLigado tempoLigado3 = new TempoLigado();
                            tempoLigado3.setDia(diaAtual);
                            tempoLigado3.setPotencia(data.getLed3());
                            tDao.create(tempoLigado3);
                            
                        }
                    
                        estado.setText(arduinoCurrentState);
                    }
                    arduino.sleep(1000);
                }
            }
        };
                
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("arduino");

        estado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        estado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estado.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(estado, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(estado, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEstado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel estado;
    // End of variables declaration//GEN-END:variables
}
